---
- name: deploy-jars to spark engine
  hosts: spark
  tasks:
    - name: deploy jars
      copy:
        src: "{{ item.src }}"
        dest: /engine/spark-3.5.1-bin-hadoop3/jars
        remote_src: no
        owner: spark
        group: spark
      loop:
        - src: /home/ec2-user/downloads/hadoop-aws-3.3.4.jar
        - src: /home/ec2-user/downloads/aws-java-sdk-bundle-1.12.769.jar
        - src: /home/ec2-user/downloads/bundle-2.23.19.jar
        - src: /home/ec2-user/downloads/wildfly-openssl-1.1.3.Final.jar
      become: yes

    - name: modify spark-defaults.conf
      blockinfile:
        path: /engine/spark-3.5.1-bin-hadoop3/conf/spark-defaults.conf
        block: |
          spark.master yarn
          spark.deploy.mode client
          spark.serializer org.apache.spark.serializer.KryoSerializer
          spark.sql.shuffle.partitions 6
          spark.hadoop.hive.metastore.uris thrift://spark03:9083
          spark.sql.warehouse.dir hdfs:///home/spark/warehouse
          spark.sql.catalogImplementation hive
          spark.sql.hive.metastore.version 3.1.2
          spark.sql.hive.metastore.jars path
          spark.sql.hive.metastore.jars.path file:///engine/spark-3.5.1-bin-hadoop3/jars_hms/*.jar,file:///engine/spark-3.5.1-bin-hadoop3/jars/*.jar
          spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
          spark.hadoop.fs.s3a.endpoint s3.ap-northeast-2.amazonaws.com
          spark.hadoop.fs.s3a.path.style.access true
          spark.hadoop.fs.s3a.access.key ##PYSPARK-APPS-ACCESS-KEY##
          spark.hadoop.fs.s3a.secret.key ##PYSPARK-APPS-SECRET-KEY##
        marker: "# {mark} Setting spark-defaults.conf"
        create: true
        owner: spark
        group: spark
      become: yes

- name: deploy-jars to hive engine
  hosts: spark03
  tasks:
    - name: deploy jars
      copy:
        src: "{{ item.src }}"
        dest: /engine/apache-hive-metastore-3.1.2-bin/lib
        remote_src: no
        owner: hadoop
        group: hadoop
      loop:
        - src: /home/ec2-user/downloads/hadoop-aws-3.3.4.jar
        - src: /home/ec2-user/downloads/aws-java-sdk-bundle-1.12.769.jar
        - src: /home/ec2-user/downloads/bundle-2.23.19.jar
        - src: /home/ec2-user/downloads/wildfly-openssl-1.1.3.Final.jar
      become: yes