---
- name: setting hadoop xml
  hosts: spark
  tasks:
    - name: setting yarn-site.xml
      blockinfile:
        path: /engine/hadoop-3.3.6/etc/hadoop/yarn-site.xml
        block: |
          <configuration>
            <property>
              <name>yarn.am.liveness-monitor.expiry-interval-ms</name>
              <value>60000</value>
            </property>
            <property>
              <name>yarn.application.classpath</name>
              <value>/engine/hadoop-3.3.6/etc/hadoop,
                     /engine/hadoop-3.3.6/share/hadoop/common/*,
                     /engine/hadoop-3.3.6/share/hadoop/common/lib/*,
                     /engine/hadoop-3.3.6/share/hadoop/hdfs/*,
                     /engine/hadoop-3.3.6/share/hadoop/hdfs/lib/*,
                     /engine/hadoop-3.3.6/share/hadoop/mapreduce/*,
                     /engine/hadoop-3.3.6/share/hadoop/mapreduce/lib/*,
                     /engine/hadoop-3.3.6/share/hadoop/yarn/*,
                     /engine/hadoop-3.3.6/share/hadoop/yarn/lib/*
              </value>
            </property>
            <property>
              <name>yarn.log-aggregation-enable</name>
              <value>true</value>
            </property>
            <property>
              <name>yarn.log-aggregation.retain-seconds</name>
              <value>259200</value>
            </property>
            <property>
              <name>yarn.nm.liveness-monitor.expiry-interval-ms</name>
              <value>60000</value>
            </property>
            <property>
              <name>yarn.nodemanager.aux-services</name>
              <value>mapreduce_shuffle</value>
            </property>
            <property>
              <name>yarn.nodemanager.aux-services.mapreduce_shuffle.class</name>
              <value>org.apache.hadoop.mapred.ShuffleHandler</value>
            </property>
            <property>
              <name>yarn.nodemanager.local-dirs</name>
              <value>/data01/yarn/rm-local-dir</value>
            </property>
            <property>
              <name>yarn.nodemanager.log-dirs</name>
              <value>/data01/yarn/logs</value>
            </property>
            <property>
              <name>yarn.nodemanager.log.retain-seconds</name>
              <value>259200</value>
            </property>
            <property>
              <name>yarn.nodemanager.remote-app-log-dir</name>
              <value>/apps/yarn/app-logs</value>
            </property>
            <property>
              <name>yarn.nodemanager.resource.cpu-vcores</name>
              <value>6</value>
            </property>
            <property>
              <name>yarn.nodemanager.resource.memory-mb</name>
              <value>8192</value>
            </property>
            <property>
              <name>yarn.resourcemanager.address.rm1</name>
              <value>spark01:8032</value>
            </property>
            <property>
              <name>yarn.resourcemanager.admin.address.rm1</name>
              <value>spark01:8033</value>
            </property>
            <property>
              <name>yarn.resourcemanager.admin.address.rm2</name>
              <value>spark02:8033</value>
            </property>
            <property>
              <name>yarn.resourcemanager.address.rm2</name>
              <value>spark02:8032</value>
            </property>
            <property>
              <name>yarn.resourcemanager.am.max-attempts</name>
              <value>4</value>
            </property>
            <property>
              <name>yarn.resourcemanager.cluster-id</name>
              <value>yarn-cluster</value>
            </property>
            <property>
              <name>yarn.resourcemanager.container.liveness-monitor.interval-ms</name>
              <value>60000</value>
            </property>
            <property>
              <name>yarn.resourcemanager.fs.state-store.uri</name>
              <value>/data01/yarn/system/rmstore</value>
            </property>
            <property>
              <name>yarn.resourcemanager.ha.enabled</name>
              <value>true</value>
            </property>
            <property>
              <name>yarn.resourcemanager.ha.rm-ids</name>
              <value>rm1,rm2</value>
            </property>
            <property>
              <name>yarn.resourcemanager.hostname</name>
              <value>spark01</value>
            </property>
            <property>
              <name>yarn.resourcemanager.hostname.rm1</name>
              <value>spark01</value>
            </property>
            <property>
              <name>yarn.resourcemanager.hostname.rm2</name>
              <value>spark02</value>
            </property>
            <property>
              <name>yarn.resourcemanager.recovery.enabled</name>
              <value>true</value>
            </property>
            <property>
              <name>yarn.resourcemanager.resource-tracker.address</name>
              <value>spark01:8031</value>
            </property>
            <property>
              <name>yarn.resourcemanager.resource-tracker.address.rm1</name>
              <value>spark01:8031</value>
            </property>
            <property>
              <name>yarn.resourcemanager.resource-tracker.address.rm2</name>
              <value>spark02:8031</value>
            </property>
            <property>
              <name>yarn.resourcemanager.scheduler.address</name>
              <value>spark01:8030</value>
            </property>
            <property>
              <name>yarn.resourcemanager.scheduler.address.rm2</name>
              <value>spark02:8030</value>
            </property>
            <property>
              <name>yarn.resourcemanager.scheduler.class</name>
              <value>org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler</value>
            </property>
            <property>
              <name>yarn.resourcemanager.webapp.address.rm1</name>
              <value>spark01:8088</value>
            </property>
            <property>
              <name>yarn.resourcemanager.webapp.address.rm2</name>
              <value>spark02:8088</value>
            </property>
            <property>
              <name>yarn.resourcemanager.zk-address</name>
              <value>spark01:2181,spark02:2181,spark03:2181</value>
            </property>
            <property>
              <name>yarn.scheduler.increment-allocation-mb</name>
              <value>1024</value>
            </property>
            <property>
                <name>yarn.scheduler.increment-allocation-vcores</name>
                <value>1</value>
            </property>
            <property>
              <name>yarn.scheduler.maximum-allocation-mb</name>
              <value>4096</value>
            </property>
            <property>
              <name>yarn.scheduler.maximum-allocation-vcores</name>
              <value>2</value>
            </property>
            <property>
              <name>yarn.scheduler.minimum-allocation-mb</name>
              <value>1024</value>
            </property>
            <property>
              <name>yarn.scheduler.minimum-allocation-vcores</name>
              <value>1</value>
            </property>
            <property>
              <name>yarn.timeline-service.version</name>
              <value>2.0f</value>
            </property>
            <property>
              <name>yarn.timeline-service.webapp.address</name>
              <value>spark01:8188</value>
            </property>
            <property>
              <name>yarn.webapp.api-service.enable</name>
              <value>true</value>
            </property>
            <property>
              <name>yarn.webapp.ui2.enable</name>
              <value>true</value>
            </property>
          </configuration>
        marker: "<!--{mark} Setting hadoop configurations from ansible-->"
      become: yes