---
- name: deploy-kafka-jars
  hosts: spark
  tasks:
    - name: deploy jars
      copy:
        src: "{{ item.src }}"
        dest: /engine/spark-3.5.1-bin-hadoop3/jars
        remote_src: no
        owner: spark
        group: spark
      loop:
        - src: /home/ec2-user/downloads/spark-streaming-kafka-0-10_2.12-2.4.0.jar
        - src: /home/ec2-user/downloads/spark-sql-kafka-0-10_2.12-3.5.2.jar
        - src: /home/ec2-user/downloads/kafka-clients-3.7.1.jar
        - src: /home/ec2-user/downloads/spark-token-provider-kafka-0-10_2.12-3.5.2.jar
        - src: /home/ec2-user/downloads/commons-pool2-2.11.1.jar
      become: yes