---
- name: install hive metastore
  hosts: spark03
  tasks:
    - name: Install apt libraries
      apt:
        pkg:
          - mysql-server=8.0.*
          - python3-mysqldb
        update_cache: true
      become: yes

    - name: daemon-reload
      systemd_service:
        daemon_reload: yes
      become: yes

    - name: Start mysql Service
      systemd_service:
        state: started
        name: mysql
        enabled: true
      become: yes

    - name: create database
      community.mysql.mysql_db:
        state: present
        name:
          - hms
        login_unix_socket: /var/run/mysqld/mysqld.sock
      become: yes

    - name: create hms_user User
      community.mysql.mysql_user:
        name: hms_user
        password: hms_user1!
        priv:
          'hms.*': 'ALL,GRANT'
        host: '%'
      become: yes

    - name: bind mysql to spark03:3306
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        state: present
        regex: '^bind-address'
        line: 'bind-address            = spark03'
      become: yes

    - name: restart mysql Service
      systemd_service:
        state: restarted
        name: mysql
      become: yes

    - name: unarchive file
      ansible.builtin.unarchive:
        src: /home/ec2-user/downloads/hive-standalone-metastore-3.1.2-bin.tar.gz
        dest: /engine
        copy: true
        owner: hadoop
        group: hadoop
      become: yes

    - name: change owner to hadoop
      file:
        path: /engine/apache-hive-metastore-3.1.2-bin
        owner: hadoop
        group: hadoop
        recurse: true
      become: yes

    - name: backup metastore-site.xml
      copy:
        src: /engine/apache-hive-metastore-3.1.2-bin/conf/metastore-site.xml
        dest: /engine/apache-hive-metastore-3.1.2-bin/conf/metastore-site.xml_old
        owner: hadoop
        group: hadoop
        remote_src: true
      become: yes

    - name: initialize metastore-site.xml
      copy:
        content: ""
        dest: /engine/apache-hive-metastore-3.1.2-bin/conf/metastore-site.xml
      become: yes

    - name: setting metastore-site.xml
      blockinfile:
        path: /engine/apache-hive-metastore-3.1.2-bin/conf/metastore-site.xml
        block: |
          <configuration>
            <property>
              <name>metastore.thrift.uris</name>
              <value>thrift://spark03:9083</value>
              <description>Thrift URI for the remote metastore</description>
            </property>
            <property>
              <name>metastore.task.threads.always</name>
              <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask</value>
            </property>
            <property>
              <name>metastore.expression.proxy</name>
              <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
            </property>
            <property>
              <name>javax.jdo.option.ConnectionURL</name>
              <value>jdbc:mysql://spark03:3306/hms?createDatabaseIfNotExist=false</value>
            </property>
            <property>
              <name>javax.jdo.option.ConnectionDriverName</name>
              <value>com.mysql.cj.jdbc.Driver</value>
            </property>
            <property>
              <name>javax.jdo.option.ConnectionUserName</name>
              <value>hms_user</value>
            </property>
            <property>
              <name>javax.jdo.option.ConnectionPassword</name>
              <value>hms_user1!</value>
            </property>
          </configuration>
        marker: "<!-- {mark} Setting hive metastore configurations from ansible-->"
      become: yes

    - name: deploy mysql jar file
      get_url:
        url: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.28/mysql-connector-java-8.0.28.jar
        dest: /engine/apache-hive-metastore-3.1.2-bin/lib
        owner: hadoop
        group: hadoop
      become: yes

    - name: add metastore path in .bashrc file
      blockinfile:
        path: /home/hadoop/.bashrc
        block: |
          export HADOOP_HOME=/engine/hadoop-3.3.6
          export HADOOP_MAPRED_HOME=$HADOOP_HOME
          export HADOOP_COMMON_HOME=$HADOOP_HOME
          export HADOOP_HDFS_HOME=$HADOOP_HOME
          export YARN_HOME=$HADOOP_HOME
          export METASTORE_HOME=/engine/apache-hive-metastore-3.1.2-bin
          export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
          export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin:$METASTORE_HOME/bin
        marker: "# {mark} Setting environment from ansible"
      become: yes