---
- name: install python libraries
  hosts: spark
  tasks:
    - name: install libraries
      become: yes
      become_user: spark
      become_method: sudo
      pip:
        requirements: /src/pyspark-apps/requirements.txt
        virtualenv: /src/spark_venv
      tags: install_libs